[project]
name = "libreoffice-converter"
version = "0.1.0"
description = "libreoffice converter"
readme = "README.md"
authors = [
    { name = "dinhanhx", email = "dinhanhx@gmail.com" }
]
requires-python = ">=3.10.20"
dependencies = [
    "fastapi[standard]",
    "fastapi-offline",
    "lxml",
    "python-docx",
    "python-multipart",
    "redis[asyncio]>=6.0",
    "uvicorn[standard]",
]

[build-system]
requires = ["uv_build>=0.11.3,<0.12.0"]
build-backend = "uv_build"
